apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: YWRtaW4=
  MONGO_INITDB_ROOT_PASSWORD: YWRtaW4xMjM=
  MONGO_URI: bW9uZ29kYjovL2FkbWluOmFkbWluMTIzQG1vbmdvOjI3MDE3L3NpdDMyM2Ri 